import React from 'react';
import classes from './lyrics.module.css';

class Lyrics extends React.Component{
    constructor(props){
        super(props);


        this.state={
            visibility: false
        }
    }

    showLyrics=() => {
        this.setState( state =>{
            if(state.visibility==true){
                return {visibility:false}
            }else{
                return {visibility:true}
            }
        })
    }

render(){
    const arr = [{
        author: 'Lana Del Rey',
        name: 'Venice Bitch',
        text: 
        [
        "Fear fun, fear love", <br />,
        "Fresh out of fucks, forever", <br />,
        "Tryin' to be stronger for you", <br />,
        "Ice cream, ice queen", <br />,
        "I dream in jeans... *sigh*", <br />,
        "Life's dream, I'm sweet for you", <br />,
        "Oh God, miss you on my lips", <br />,
        "It's me, your little Venice bitch", <br />,
        "On the stoop with the neighborhood kids", <br />,
        "Callin' out, bang bang, kiss kiss", <br />,
        "You're in the yard, I light the fire", <br />,
       "And as the summer fades away", <br />,
        "Nothing gold can stay", <br />,
        "You write, I tour, we make it work", <br />,
        "You're beautiful and I'm insane", <br />,
        "We're American-made", <br />,
        "Give me Hallmark", <br />,
        "One dream, one life, one lover", <br />,
        "Paint me happy and blue", <br />,
        "Norman Rockwell", <br />,
        "No hype under our covers", <br />,
        "It's just me and you", <br />,
        "Oh God, miss you on my lips", <br />,
        "It's me, your little Venice bitch", <br />,
        "On the stoop with the neighborhood kids", <br />,
        "Callin' out, bang bang, kiss kiss", <br />,
        "You're in the yard, I light the fire", <br />,
        "And as the summer fades away", <br />,
        "Nothing gold can stay", <br />,
        "You write, I tour, we make it work", <br />,
        "You're beautiful and I'm insane", <br />,
        "We're American-made", <br />,
        "Oh yeah, oh yeah, oh yeah", <br />,
        "Signin' off, bang bang, kiss kiss", <br />,
        "Yeah yeah, oh yeah, oh yeah", <br />,
        "Signin' off, bang bang, kiss kiss", <br />,
        "Oh god, want you on my lips (I do, I do)", <br />,
        "It's me, your little Venice bitch", <br />,
        "On the stoop with the neighborhood kids", <br />,
        "Signin' off, bang bang, kiss kiss", <br />,
        "Oh yeah, oh yeah, oh yeah", <br />,
        "(Signin' off, bang bang, kiss kiss)", <br />,
        "Yeah, yeah, yeah", <br />,
        "Yeah, yeah", <br />,
        "Young baby is back in town now", <br />,
        "You should come, come over", <br />,
        "We'll be hanging around now", <br />,
        "You should come, come over", <br />,
        "Oh God, I love him on my lips", <br />,
        "It's me, your little Venice bitch", <br />,
        "Touch me with your fingertips", <br />,
        "It's me, your little Venice bitch", <br />,
        "Ba-back in the garden", <br />,
        "We're getting high now, because we're older", <br />,
        "Me, myself, I like diamonds", <br />,
        "My baby, crimson and clover", <br />,
        "Oh, oh, oh, oh, whatever", <br />,
        "Everything, whatever", <br />,
        "Oh, oh, oh, oh, whatever", <br />,
        "Everything, whatever", <br />,
        "Back in the garden", <br />,
        "We're getting high now, because we're older", <br />,
        "Me, myself, I like diamonds", <br />,
        "My baby, crimson and clover", <br />,
        "Crimson and clover, honey", <br />,
        "Crimson and clover, honey", <br />,
        "Crimson and clover, honey", <br />,
        "Crimson and clover, honey", <br />,
        "Crimson and clover, honey", <br />,
        "Crimson and clover, honey", <br />,
        "Over and over, honey", <br />,
        "Over and over, honey", <br />,
        "Over and over, honey", <br />,
        "Over and over, honey", <br />,
        "Over and over", <br />,
        "If you weren't mine, I'd be", <br />,
        "Jealous of your love", <br />,
        "If you weren't mine, I'd be", <br />,
        "Jealous of your love", <br />,
        "If you weren't mine, I'd be", <br />,
        "Jealous of your love", <br />,
        "If you weren't mine, I'd be", <br />,
        "Jealous of your loved", <br />,
        "If you weren't mine, I'd be", <br />,
        "Jealous of your love"
    ],
    linkk: 'Qg3DxELVPj4'
    },

    {
        author: 'ZAYN ft. Sia',
        name: ' Dusk Till Dawn',
        text: 
        [   "Not tryna be indie", <br />,
            "Not tryna be cool", <br />,
            "Just tryna be in this", <br />,
            "Tell me how you choose", <br />,
            "Can you feel why you're in this", <br />,
            "Can you feel it through", <br />,
            "All of the windows", <br />,
            "Inside this room", <br />,
            "'Cause I wanna touch you, baby", <br />,
            "And I wanna feel you, too", <br />,
            "I wanna see the sunrise and your sins", <br />,
            "Just me and you", <br />,
            "Light it up, on the run", <br />,
            "Let's make love, tonight", <br />,
            "Make it up, fall in love, try", <br />,
            "But you'll never be alone", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll hold you when things go wrong", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "We were shut like a jacket", <br />,
            "So do your zip", <br />,
            "We will roll down the rapids", <br />,
            "To find a wave that fits", <br />,
            "Can you feel where the wind is", <br />,
            "Can you feel it through", <br />,
            "All of the windows", <br />,
            "Inside this room", <br />,
            "'Cause I wanna touch you, baby", <br />,
            "I wanna feel you, too", <br />,
            "I wanna see the sunrise and your sins", <br />,
            "Just me and you", <br />,
            "Light it up, on the run", <br />,
            "Let's make love tonight", <br />,
            "Make it up, fall in love, try", <br />,
            "But you'll never be alone", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll hold you when things go wrong", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "Go, give love to your body", <br />,
            "It's only you that can stop it", <br />,
            "Go, give love to your body", <br />,
            "It's only you that can stop it", <br />,
            "Go, give love to your body", <br />,
            "It's only you that can stop it", <br />,
            "Go, give love to your body", <br />,
            "Go, give love to your body", <br />,
            "But you'll never be alone", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll hold you when things go wrong", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here"],

        linkk: 'tt2k8PGm-TI'
    },








    {
        author: 'James Young',
        name: 'Infinity',
        text: 
        [   "Oh, oh", <br />,
           "Oh, oh, oh", <br />,
           "Oh, oh", <br />,
            "Oh, oh, oh", <br />,
            "Baby, this love, I'll never let it die", <br />,
            "Can't be touched by no one", <br />,
            "I'd like to see 'em try", <br />,
            "I'm a mad man for your touch, girl, I've lost control", <br />,
            "I'm gonna make this last forever, don't tell me it's impossible", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "Oh, darling, my soul", <br />,
            "You know it aches for yours", <br />,
            "And you've been filling this hole, since you were born, oh", <br />,
            "'Cause you're the reason I believe in fate", <br />,
            "You're my paradise", <br />,
            "And I'll do anything to be your love, or be your sacrifice", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "Meet me at the bottom of the ocean", <br />,
            "Where the time is frozen", <br />,
            "Where all the universe is open", <br />,
            "Love isn't random, we are chosen", <br />,
            "And we could wear the same crown", <br />,
            "Keep slowing your heart down", <br />,
            "We are the gods now", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)" ],

        linkk: 'PWqEPKduGm8'
    },





    {
        author: 'Jp Saxe ft. Julia Michaels',
        name: 'If The World Was Ending',
        text: 
        [   "I was distracted", <br />,
            "And in traffic", <br />,
            "I didn't feel it", <br />,
            "When the earthquake happened", <br />,
            "But it really got me thinkin'", <br />,
            "Were you out drinkin'", <br />,
            "Were you in the living room", <br />,
            "Chillin' watchin' television", <br />,
            "It's been a year now", <br />,
            "Think I've figured out how", <br />,
            "How to let you go and let communication die out", <br />,
            "I know, you know, we know, you weren't down for forever and it's fine", <br />,
            "I know, you know, we know, we weren't meant for each other and it's fine", <br />,
            "But if the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over and you'd stay the night", <br />,
            "Would you love me for the hell of it", <br />,
            "All our fears would be irrelevant", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "The sky'd be falling and I'd hold you tight", <br />,
            "And there wouldn't be a reason why", <br />,
            "We would even have to say goodbye", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "Right?", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "Right?", <br />,
            "I tried to imagine", <br />,
            "Your reaction", <br />,
            "It didn't scare me when the earthquake happened", <br />,
            "But it really got me thinkin'", <br />,
            "That night we went drinkin'", <br />,
            "Stumbled in the house", <br />,
            "And didn't make it past the kitchen", <br />,
            "Ah it's been a year now", <br />,
            "Think I've figured out how", <br />,
            "How to think about you without it rippin' my heart out", <br />,
            "I know, you know, we know, you weren't down for forever and it's fine", <br />,
            "I know, you know, we know, we weren't meant for each other and it's fine", <br />,
            "But if the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over and you'd stay the night", <br />,
            "Would you love me for the hell of it", <br />,
            "All our fears would be irrelevant", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "The sky'd be falling while I'd hold you tight", <br />,
            "No there wouldn't be a reason why", <br />,
            "We would even have to say goodbye", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over right", <br />,
            "You'd come over, you'd come over, you'd come over right", <br />,
            "I know, you know, we know, you weren't down for forever and it's fine", <br />,
            "I know, you know, we know, we weren't meant for each other and it's fine", <br />,
            "But if the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over and you'd stay the night", <br />,
            "Would you love me for the hell of it", <br />,
            "All our fears would be irrelevant", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "The sky'd be falling while I'd hold you tight", <br />,
            "No there wouldn't be a reason why", <br />,
            "We would even have to say goodbye", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over, you'd come over, you'd come over right", <br />,
            "If the world was ending", <br />,
            "You'd come over right"
         ],

        linkk: '1jO2wSpAoxA'
    },



    {
        author: 'Lewis Capaldi',
        name: 'Someone You Loved',
        text: 
        [   "I'm going under and this time I fear there's no one to save me", <br />,
        "This all or nothing really got a way of driving me crazy", <br />,
        "I need somebody to heal", <br />,
        "Somebody to know", <br />,
        "Somebody to have", <br />,
        "Somebody to hold", <br />,
        "It's easy to say", <br />,
        "But it's never the same", <br />,
        "I guess I kinda liked the way you numbed all the pain", <br />,
        "Now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
       "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "I'm going under and this time I fear there's no one to turn to", <br />,
        "This all or nothing way of loving got me sleeping without you", <br />,
        "Now, I need somebody to know", <br />,
        "Somebody to heal", <br />,
        "Somebody to have", <br />,
        "Just to know how it feels", <br />,
        "It's easy to say but it's never the same", <br />,
        "I guess I kinda liked the way you helped me escape", <br />,
        "Now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "And I tend to close my eyes when it hurts sometimes", <br />,
        "I fall into your arms", <br />,
        "I'll be safe in your sound 'til I come back around", <br />,
        "For now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "But now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved"
         ],

        linkk: 'zABLecsR5UE'
    },






    {
        author: 'The Young Professionals',
        name: 'Video Games',
        text: 
        [   "Swinging in the backyard", <br />,
        "Pull up in your fast car whistling my name", <br />,
        "Open up a beer", <br />,
        "And you say get over here and play a video game", <br />,
        "I'm in his favorite sun dress", <br />,
        "Watching me get undressed take that body downtown", <br />,
        "I say you the bestest", <br />,
        "Lean in for a big kiss put his favorite perfume on", <br />,
        "Go play your video game", <br />,
        "It's you, it's you, it's all for you", <br />,
        "Everything I do", <br />,
        "I tell you all the time", <br />,
        "Heaven is a place on earth where you", <br />,
        "Tell me all the things you want to do", <br />,
        "I heard that you like the bad girls honey, is that true?", <br />,
        "It's better than I ever even knew", <br />,
        "They say that the world was built for two", <br />,
       "Only worth living if somebody is loving you", <br />,
        "Baby now you do", <br />,
        "Singing in the old bars", <br />,
        "Swinging with the old stars", <br />,
        "Living for the fame", <br />,
        "Kissing in the blue dark", <br />,
        "Playing pool and wild darts", <br />,
        "Video games", <br />,
        "He holds me in his big arms", <br />,
        "Drunk and I am seeing stars", <br />,
        "This is all I think of", <br />,
        "Watching all our friends fall", <br />,
        "In and out of Old Paul's", <br />,
        "This is my idea of fun", <br />,
        "Playing video games", <br />,
        "It's you, it's you, it's all for you", <br />,
        "Everything I do", <br />,
        "I tell you all the time", <br />,
        "Heaven is a place on earth where you", <br />,
        "Tell me all the things you want to do", <br />,
        "I heard that you like the bad girls honey, is that true?", <br />,
        "It's better than I ever even knew", <br />,
        "They say that the world was built for two", <br />,
        "Only worth living if somebody is loving you", <br />,
        "Baby now you do (now you do)", <br />,
        "It's you, it's you, it's all for you", <br />,
        "Everything I do", <br />,
        "I tell you all the time", <br />,
        "Heaven is a place on earth where you", <br />,
        "Tell me all the things you want to do", <br />,
        "I heard that you like the bad girls honey, is that true?", <br />,
        "It's better than I ever even knew", <br />,
        "They say that the world was built for two", <br />,
        "Only worth living if somebody is loving you", <br />,
        "Baby now you do (now you do)", <br />,
        "Now you do (now you do)"
         ],

        linkk: 'sexPTYJ4fbo'
    },




    {
        author: 'James Young',
        name: 'Happiest Year',
        text: 
        [   "I'm really on the ropes this time", <br />,
        "I've been fighting all my life for you", <br />,
        "I never should have said goodbye", <br />,
        "But maybe that's what stupid people do", <br />,
        "'Cause you gave me peace", <br />,
        "And I wasted it", <br />,
        "I'm here to admit", <br />,
        "That you were my medicine", <br />,
        "Oh, I couldn't quit", <br />,
        "And I'm down on my knees again", <br />,
        "Asking", <br />,
        "For nothing", <br />,
        "Thank you for the happiest year of my life", <br />,
        "Thank you for the happiest year of my life, ooh", <br />,
        "Ooh, ooh, ooh", <br />,
       "Don't think I could forgive myself", <br />,
        "I'm sorry for the ways that I used you", <br />,
        "And I could care less right now", <br />,
        "But you know, you hurt me pretty good too", <br />,
        "Yeah, we made each other bleed", <br />,
        "And we tasted it", <br />,
        "I'm here to admit", <br />,
        "That you were my medicine", <br />,
        "Oh, love, I couldn't quit", <br />,
        "And I'm down on my knees again", <br />,
        "Thank you for the happiest year of my life, oh", <br />,
        "Thank you for the happiest year of my life, ooh", <br />,
        "So wake me up when they build that time machine", <br />,
        "I want to go back", <br />,
        "Wake me up when you were sleeping next to me", <br />,
        "'Cause I really loved you, ooh", <br />,
        "Thank you for the happiest year of my life", <br />,
        "Thank you for the happiest year of my life ohh", <br />,
        "Thank you for the happiest year of my life, yeah", <br />,
        "Thank you for the happiest year of my life", <br />,
        "Thank you for the happiest year of my life"
         ],

        linkk: 'v9GLAUWJNG0'
    },


    {
        author: 'TONES AND I',
        name: 'DANCE MONKEY',
        text: 
        [   "They say, oh my god, I see the way you shine", <br />,
        "Take your hands, my dear, and place them both in mine", <br />,
        "You know you stopped me dead while I was passing by", <br />,
        "And now I beg to see you dance just one more time", <br />,
        "Ooh I see you, see you, see you every time", <br />,
        "And, oh my, I, I, I like your style", <br />,
        "You, you make me, make me, make me wanna cry", <br />,
        "And now I beg to see you dance just one more time", <br />,
        
        "So they say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done, I'll make you do it all again", <br />,
        "I said, oh my god, I see you walking by", <br />,
        "Take my hands, my dear, and look me in my eyes", <br />,
        "Just like a monkey I've been dancing my whole life", <br />,
        "But you just beg to see me dance just one more time", <br />,
        "Ooh I see you, see you, see you every time", <br />,
        "And, oh my, I, I, I,", <br />,
        "I like your style", <br />,
        "You, you make me, make me, make me wanna cry", <br />,
        "And now I beg to see you dance just one more time", <br />,
        
        "So they say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        
        "They say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        
        "They say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        "They say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        "All again "
         ],

        linkk: 'q0hyYWKXF0Q'
    },


    {
        author: 'Pascal Letoublon',
        name: 'Friendships',
        text: 
        [
            " ",<br />,
         ],

        linkk: '5rmb7WhmW30'
    },


    {
        author: 'Christina Perri',
        name: 'Human',
        text: ["I can hold my breath", <br />,
        "I can bite my tongue", <br />,
        "I can stay awake for days", <br />,
        "If that's what you want", <br />,
        "Be your number one", <br />,
        "I can fake a smile", <br />,
        "I can force a laugh", <br />,
        "I can dance and play the part", <br />,
        "If that's what you ask", <br />,
       "Give you all I am", <br />,
        "I can do it", <br />,
        "I can do it", <br />,
        "I can do it", <br />,
        "But I'm only human", <br />,
        "And I bleed when I fall down", <br />,
        "I'm only human", <br />,
        "And I crash and I break down", <br />,
        "Your words in my head, knives in my heart", <br />,
        "You build me up and then I fall apart", <br />,
        "'Cause I'm only human, yeah", <br />,
        "I can turn it on", <br />,
        "Be a good machine", <br />,
        "I can hold the weight of worlds", <br />,
        "If that's what you need", <br />,
        "Be your everything", <br />,
        "I can do it", <br />,
        "I can do it", <br />,
        "I'll get through it", <br />,
        "But I'm only human", <br />,
        "And I bleed when I fall down", <br />,
        "I'm only human", <br />,
        "And I crash and I break down", <br />,
        "Your words in my head, knives in my heart", <br />,
        "You build me up and then I fall apart", <br />,
        "'Cause I'm only human, yeah", <br />,
        "I'm only human", <br />,
        "I'm only human", <br />,
        "Just a little human", <br />,
        "I can take so much", <br />,
        "Until I've had enough", <br />,
        "'Cause I'm only human", <br />,
        "And I bleed when I fall down", <br />,
        "I'm only human", <br />,
        "And I crash and I break down", <br />,
        "Your words in my head, knives in my heart", <br />,
        "You build me up and then I fall apart", <br />,
        "'Cause I'm only human, yeah"],

        linkk: '5rmb7WhmW30'
    },


    {
        author: 'James Bay',
        name: 'Let It Go',
        text: ["From walking home and talking loads", <br />,
        "To seeing shows in evening clothes with you", <br />,
        "From nervous touch and getting drunk", <br />,
        "To staying up and waking up with you", <br />,
        "Now we're slipping near the edge", <br />,
        "Holding something we don't need", <br />,
        "Oh, this delusion in our heads", <br />,
        "Is gonna bring us to our knees", <br />,
        "So come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "Everything that's broke", <br />,
        "Leave it to the breeze", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "And I'll be me", <br />,
        "From throwing clothes across the floor", <br />,
        "To teeth and claws and slamming doors at you", <br />,
        "If this is all we're living for", <br />,
        "Why are we doing it, doing it, doing it anymore?", <br />,
        "I used to recognize myself", <br />,
        "It's funny how reflections change", <br />,
        "When we're becoming something else", <br />,
        "I think it's time to walk away", <br />,
        "So come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "Everything that's broke", <br />,
        "Leave it to the breeze", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "And I'll be me", <br />,
        "Tryna fit your hand inside mine", <br />,
        "When we know it just don't belong", <br />,
        "There's no force on earth", <br />,
        "Could make it feel right, no", <br />,
        "Tryna push this problem up the hill", <br />,
        "When it's just too heavy to hold", <br />,
        "Think now is the time to let it slide", <br />,
        "So come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "Everything that's broke", <br />,
        "Leave it to the breeze", <br />,
        "Let the ashes fall", <br />,
        "Forget about me", <br />,
        "Come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "And I'll be me"],

        linkk: 'GsPq9mzFNGY'
    },





    {
        author: 'Alec Benjamin',
        name: 'The Water Fountain',
        text: 
        ["She told me that she loved me by the water fountain", <br />,
        "She told me that she loved me and she didn't love him", <br />,
        "And that was really lovely 'cause it was innocent", <br />,
        "But now she's got a cup with something else in it", <br />,
        "It's getting kind of blurry at a quarter-past-ten", <br />,
        "And he was in a hurry to be touching her skin", <br />,
        "She's feeling kind of dirty when she's dancing with him", <br />,
        "Forgetting what she told me by the water fountain", <br />,
        "Now he's grabbing her hips, and pulling her in", <br />,
        "Kissing her lips, and whispering in her ear", <br />,
        "And she knows that she shouldn't listen", <br />,
        "And that she should be with me by the water fountain", <br />,
        "She couldn't be at home in the night time because", <br />,
        "It made her feel alone, but at that time she was too young", <br />,
        "I was too young", <br />,
        "I should've built a home with a fountain for us", <br />,
        "The moment that she told me that she was in love too young", <br />,
        "I was too young", <br />,
        "Too young, too young", <br />,
        "Too young, young", <br />,
        "And if she ever goes back to the water fountain", <br />,
        "The handle will be broken and the rust set in", <br />,
        "But my hand, it will be open and I'll try to fix it", <br />,
        "My heart, it will be open and I'll try to give it", <br />,
        "Now I'm grabbing her hips, and pulling her in", <br />,
        "Kissing her lips, and whispering in her ear", <br />,
        "And I know that it's only a wish", <br />,
        "And that we're not standing by the water fountain", <br />,
        "Too young, too young", <br />,
        "Too young, young", <br />,
        "She couldn't be at home in the night time because", <br />,
        "It made her feel alone but at that time she was too young", <br />,
        "I was too young", <br />,
        "I should've built a home with a fountain for us", <br />,
        "The moment that she told me that she was in love too young", <br />,
        "I was too young", <br />,
        "Too young, too young", <br />,
        "Too young, young", <br />,
        "I should've built a home with a fountain for us", <br />,
        "(Too young) the moment that she told me that she was in love", <br />,
        "(Too young) too young", <br />,
        "(Young) I was too young"],
        linkk: '5ado75KpV9w'
    },

    


    {
        author: 'LP',
        name: 'Lost On You',
        text: ["When you get older, plainer, saner", <br />,
        "When you remember all the danger we came from", <br />,
        "Burning like embers, falling, tender", <br />,
        "Long before the days of no surrender", <br />,
        "Years ago and well you know", <br />,
        "Smoke 'em if you got 'em", <br />,
        "'Cause it's going down", <br />,
        "All I ever wanted was you", <br />,
        "I'll never get to heaven", <br />,
        "'Cause I don't know how", <br />,
        "Let's raise a glass or two", <br />,
        "To all the things I've lost on you", <br />,
        "Oh oh", <br />,
        "Tell me are they lost on you?", <br />,
        "Oh oh", <br />,
        "Just that you could cut me loose", <br />,
        "Oh oh", <br />,
        "After everything I've lost on you", <br />,
        "Is that lost on you?", <br />,
        "Oh oh", <br />,
        "Is that lost on you?", <br />,
        "Oh oh", <br />,
        "Baby, is that lost on you?", <br />,
        "Is that lost on you?", <br />,
        "Wishing I could see the machinations", <br />,
        "Understand the toil of expectations in your mind", <br />,
        "Hold me like you never lost your patience", <br />,
        "Tell me that you love me more than hate me all the time", <br />,
        "And you're still mine", <br />,
        "So smoke 'em if you've got 'em", <br />,
        "'Cause it's going down", <br />,
        "All I ever wanted was you", <br />,
        "Let's take a drink of heaven", <br />,
        "This can turn around", <br />,
        "Let's raise a glass or two", <br />,
        "To all the things I've lost on you", <br />,
        "Oh oh", <br />,
        "Tell me are they lost on you?", <br />,
        "Oh oh", <br />,
        "Just that you could cut me loose", <br />,
        "Oh oh", <br />,
        "After everything I've lost on you", <br />,
        "Is that lost on you?", <br />,
        "Oh oh", <br />,
        "Is that lost on you?", <br />,
        "Oh oh, oh oh", <br />,
        "Bab, is that lost on you?", <br />,
        "Is that lost on you?", <br />,
        "Let's raise a glass or two", <br />,
        "To all the things I've lost on you", <br />,
        "Oh oh", <br />,
        "Tell me are they lost on you?", <br />,
        "Oh oh", <br />,
        "Just that you cold cut me loose", <br />,
        "Oh oh", <br />,
       "After everything I've lost on you", <br />,
        "Is that lost on you?", <br />,
        "Is that lost on you?"],

        linkk: 'hn3wJ1_1Zsg'
    },


    {
        author: 'Frames',
        name: "Don't Stay Here",
        text: 
        [
            " ",<br />,
         ],
        linkk: '1knh-_SYrfQ'
    },


    {
        author: 'Ashe',
        name: "Moral of the Story",
        text: ["So I never really knew you", <br />,
        "God I really tried to", <br />,
        "Blindsided, addicted", <br />,
        "Felt we could really do this", <br />,
        "But really I was foolish", <br />,
        "Hindsight it's", <br />,
        "Obvious", <br />,
        "Talking with my lawyer she said", <br />,
        "Where'd you find this guy?", <br />,
        'I said, "Young people fall in love"', <br />,
        '"With the wrong people sometimes"', <br />,
        "Some mistakes get made", <br />,
        "That's alright, that's okay", <br />,
        "You can think that you're in love", <br />,
        "When you're really just in pain", <br />,
        "Some mistakes get made", <br />,
        "That's alright, that's okay", <br />,
        "In the end it's better for me", <br />,
        "That's the moral of the story babe", <br />,
        "Oh, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Woo, oh", <br />,
        "Oh-ooh", <br />,
        "It's funny how a memory", <br />,
        "Turns into a bad dream", <br />,
        "When running wild turns volatile", <br />,
        "Remember how we painted our house?", <br />,
        "Just like my grandparents did, so romantic", <br />,
        "But we fought the whole time", <br />,
        "Should have seen the signs, yeah", <br />,
        "Talking with my mother she said", <br />,
        "Where'd you find this guy?", <br />,
        'I said, "Some people fall in love"', <br />,
        '"With the wrong people sometimes"', <br />,
        'Some mistakes get made', <br />,
        "That's alright, that's okay", <br />,
        "You can think that you're in love", <br />,
        "When you're really just in pain", <br />,
        "Some mistakes get made", <br />,
        "That's alright, that's okay", <br />,
        "In the end it's better for me", <br />,
        "That's the moral of the story babe", <br />,
        "Oh, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Woo, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Oh, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Woo, oh", <br />,
        "Oh-ooh", <br />,
        "They say it's better to have loved and lost", <br />,
        "Than never to have loved at all", <br />,
        "That could be a load of shit", <br />,
        "But I just need to tell you all", <br />,
        "Some mistakes get made", <br />,
       "That's alright, that's okay", <br />,
        "You can think that you're in love", <br />,
        "When you're really just engaged", <br />,
        "Some mistakes get made", <br />,
        "That's alright, that's okay", <br />,
        "In the end it's better for me", <br />,
        "That's the moral of the story", <br />,
        "Some mistakes get made", <br />,
        "That's alright, that's okay", <br />,
        "You can think that you're in love", <br />,
        "When you're really just in pain", <br />,
        "Some mistakes get made", <br />,
        "That's alright, that's okay", <br />,
        "In the end it's better for me", <br />,
        "That's the moral of the story babe", <br />,
        "Oh, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Woo, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Oh, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Woo, oh", <br />,
        "Oh-ooh, oh", <br />,
        "Oh, oh", <br />,
        "Oh-ooh-oh", <br />,
        "Woo, oh", <br />,
        "Oh-ooh"],
        linkk: 'WQq98YPV8yk'
    },



    {
        author: 'Lana Del Rey',
        name: 'Mariners Apartment Complex',
        text: 
        [
        "You took my sadness out of context", <br />,
"At the Mariners Apartment Complex",<br />,
"I ain't no candle in the wind",<br />,
"I'm the board, the lightning, the thunder",<br />,
"Kind of girl who's gonna make you wonder",<br />,
"Who you are and who you've been",<br />,
"And who I've been is with you on these beaches",<br />,
"Your Venice bitch, your die-hard, your weakness",<br />,
"Maybe I could save you from your sins",<br />,
"So, kiss the sky and whisper to Jesus",<br />,
"My, my, my, you found this, you need this",<br />,
"Take a deep breath, baby, let me in",<br />,
"You lose your way, just take my hand",<br />,
"You're lost at sea, then I'll command your boat to me again",<br />,
"Don't look too far, right where you are, that's where I am",<br />,
"I'm your man",<br />,
"I'm your man",<br />,
"They mistook my kindness for weakness",<br />,
"I fucked up, I know that, but Jesus",<br />,
"Can't a girl just do the best she can?",<br />,
"Catch a wave and take in the sweetness",<br />,
"Think about it, the darkness, the deepness",<br />,
"All the things that make me who I am",<br />,
"And who I am is a big-time believer",<br />,
"That people can change, but you don't have to leave her",<br />,
"When everyone's talking, you can make a stand",<br />,
"'Cause even in the dark I feel your resistance",<br />,
"You can see my heart burning in the distance",<br />,
"Baby, baby, baby, I'm your man (yeah)",<br />,
"You lose your way, just take my hand",<br />,
"You're lost at sea, then I'll command your boat to me again",<br />,
"Don't look too far, right where you are, that's where I am",<br />,
"I'm your man",<br />,
"I'm your man",<br />,
"Catch a wave and take in the sweetness",<br />,
"Take in the sweetness",<br />,
"You want this, you need this",<br />,
"Are you ready for it?",<br />,
"Are you ready for it? Are you ready for it?"
         ],

        linkk: '1uFv9Ts7Sdw'
    },


    {
        author: 'Eden',
        name: 'Wake Up',
        text: 
        [
        "'Cause we've been driving so long",<br />,
        "I can't remember how we got here",<br />,
        "Or how we survived so long",<br />,
        "I'm trying to run from our pride",<br />,
        "'Til you set fire to my atmosphere",<br />,
        "And I remember how I spent the twenty-third",<br />,
        "Feeling six feet under",<br />,
        "When I'm 30, 000 feet in the air",<br />,
        "Chasing that sundown",<br />,
        "So far East, I'm Westbound",<br />,
        "Feeling like the edge of this world is near",<br />,
        "But you'll feel better when you wake up",<br />,
        "Swear to God I'll make up",<br />,
        "Everything and more when I get back someday",<br />,
        "This is more than just a phase, love",<br />,
        "Shooting stars all break up",<br />,
        "And even though it seems like half the world away",<br />,
        "Things will be better in America",<br />,
        "Heard the streets are gold there",<br />,
        "Maybe I can fly you out this place someday",<br />,
        "Chasing dreams like I'm on novocain",<br />,
        "Screaming through your airways",<br />,
        "Looking back, I almost thought I heard you say",<br />,
        "Stay, you're not gonna leave me",<br />,
        "This place is right where you need to be",<br />,
        "And why your words gotta mean so much to them",<br />,
        "And they mean nothing to me?",<br />,
        "So stay, you're not what you're hearing",<br />,
        "'Cause I've been watching you changing",<br />,
        "And who said you're one in a million",<br />,
        "Anyway?",<br />,
        "'Cause you see only what you want to",<br />,
        "Your tunnel vision haunts you",<br />,
        "And you can't see what's wrong",<br />,
        "And you keep sleeping through the PM",<br />,
        "Eyes wide open when you're dreaming",<br />,
        "You're sleepwalking, just keep talking",<br />,
        "And maybe you can talk your way out of this deep end",<br />,
        "No B plan in your system",<br />,
        "Just tell me what you're thinking",<br />,
        "I'm scared that you might fall",<br />,
        "But you're not",<br />,
        "But you're not",<br />,
        "And you'll feel better when you wake up",<br />,
        "Taking off your makeup",<br />,
        "Sun always seems to wash our fears away",<br />,
        "And it's always shining somewhere",<br />,
        "I just gotta get there",<br />,
        "And even though it seems like half the world away",<br />,
        "Things are better in America",<br />,
        "Heard the streets are gold there",<br />,
        "Maybe I can fly you out this place someday",<br />,
        "Chasing dreams like I'm on novocain",<br />,
        "Screaming through your airways",<br />,
        "Looking back, I almost thought I heard you say",<br />,
        "Stay, you're not gonna leave me",<br />,
        "This place is right where you need to be",<br />,
        "And why your words gotta mean so much to them",<br />,
        "When they mean nothing to me",<br />,
        "So stay, you're not what you're hearing",<br />,
        "'Cause I've been watching you changing",<br />,
        "And who said you're one in a million",<br />,
        "You're so much better than that",<br />,
        "(Ohhhh)",<br />,
        "You're so much better than that (Ohh)",<br />,
        "(Ohhhh)",<br />,
        "You're so much better than that (Ohh)",<br />,
        "Stay, you're not what you were hearing (Ohh)",<br />,
        "'Cause I've been watching you changing (Ohh)",<br />,
        "And who said you're one in a million (Ohh)",<br />,
        "Anyway?",<br />,
        "And you'll feel better when you wake up",<br />,
        "Swear to God I'll make up",<br />,
        "Everything or more when I get back someday",<br />,
        "Chasing dreams like I'm on novocain",<br />,
        "Screaming through your airways",<br />,
        "Looking back, I almost thought I heard you say",<br />,
        "You're so much better than that"
         ],

        linkk: 'YthChN1Wq8M'
    },


    {
        author: 'Old Man Canyon',
        name: 'Phantoms and Friends',
        text: 
        [
        "When I awoke I felt the call to go",<br />,
        "Those places that I never thought I'd go",<br />,
        "I spent the time to see which way to walk",<br />,
        "But now that road just crumbles as I talk",<br />,
        "Don't let the ones that want to steal your dreams",<br />,
        "They'll steal your dreams away",<br />,
        "Just laugh and let it go",<br />,
        "Don't let the ones that want to steal your dreams",<br />,
        "They'll steal your dreams away",<br />,
        "Just laugh and let it go",<br />,
        "So you've tried to pass along your doubt",<br />,
        "Oh you need somebody's ears to hear you shout",<br />,
        "All your wasted days and twisted ways are up",<br />,
        "So now its time to see the cards you're dealt",<br />,
        "Don't let the ones that want to steal your dreams",<br />,
        "They'll steal your dreams away",<br />,
        "Just laugh and let it go",<br />,
        "I know all your names",<br />,
        "Pointing different ways",<br />,
        "Let me out",<br />,
        "I came up I saw you there",<br />,
        "Now I know",<br />,
        "Now I know",<br />,
        "I rose up my fear was gone",<br />,
        "Now I know",<br />,
        "Now I know",<br />,
        "Don't let the ones that want to steal your dreams",<br />,
        "They'll steal your dreams away",<br />,
        "Just laugh and let it go",<br />,
        "Don't let the ones that want to steal your dreams",<br />,
        "They'll steal your dreams away",<br />,
        "Just laugh and let it go"
         ],

        linkk: 'hzIGIBQXVqA'
    },


    {
        author: 'Maybeshewill',
        name: 'He Films The Clouds Pt. 2',
        text: 
        ["Now we're apart.",<br />,
        "Though not through choice.",<br />,
        "Do we stay mute?",<br />,
        "Or raise our voice?",<br />,
        "Now we're apart.",<br />,
        "Though not through choice.",<br />,
        "Do we stay mute?",<br />,
        "Or raise our voice?",<br />,
        "Now we're apart.",<br />,
        "Though not through choice.",<br />,
        "Do we stay mute?",<br />,
        "Or raise our voice?"
         ],

        linkk: 'lVopcyHcEgU'
    },


    {
        author: 'Trevor Daniel',
        name: "Falling",
        text: 
        ["My last made me feel like I would never try again",<br />,
        "But when I saw you, I felt something I never felt",<br />,
        "Come closer, I'll give you all my love",<br />,
        "If you treat me right, baby, I'll give you everything",<br />,
        "My last made me feel like I would never try again",<br />,
        "But when I saw you, I felt something I never felt",<br />,
        "Come closer, I'll give you all my love",<br />,
        "If you treat me right, baby, I'll give you everything",<br />,
        "Talk to me, I need to hear you need me like I need you",<br />,
        "Fall for me, I wanna know you feel how I feel for you, love",<br />,
        "Before you, baby, I was numb, drown the pain by pouring up",<br />,
        "Speeding fast on the run, never want to get caught up",<br />,
        "Now you the one that I'm calling",<br />,
        "Swore that I'd never forget, don't think I'm just talking",<br />,
        "I think I might go all in, no exceptions, girl, I need ya",<br />,
        "Feeling like I'm out of my mind, 'cause I can't get enough",<br />,
        "Only one that I give my time, 'cause I got time for ya",<br />,
        "Might make an exception for ya, 'cause I been feeling ya",<br />,
        "Think I might be out of my mind, I think that you're the one",<br />,
        "My last made me feel like I would never try again",<br />,
        "But when I saw you, I felt something I never felt",<br />,
        "Come closer, I'll give you all my love",<br />,
        "If you treat me right, baby, I'll give you everything",<br />,
        "My last made me feel like I would never try again",<br />,
        "But when I saw you, I felt something I never felt",<br />,
        "Come closer, I'll give you all my love",<br />,
        "If you treat me right, baby, I'll give you everything",<br />,
        "I'll never give my all again",<br />,
        "'Cause I'm sick of falling down",<br />,
        "When I open up and give my trust",<br />,
        "They find a way to break it down",<br />,
        "Tear me up inside, and you break me down"
         ],

        linkk: 'L7mfjvdnPno'
    },


    {
        author: 'Mudflow',
        name: 'The Sense of me / Chemicals',
        text: 
        ["Try to try again" ,<br />,
        "To hear yourself again from time to time",<br />,
        "Try to try again",<br />,
        "To hear yourself again from time to time",<br />,
        "Try to try again",<br />,
        "To hear yourself again from time to time",<br />,

        "Just another party where the people dance alone",<br />,
        "Everybody's trying to have some fun",<br />,
        "Neonlights are buzzing round my head",<br />,
        "I feel the sense of me",<br />,
        "The sublime after-glow of inner peace",<br />,
        "Just a tiny point lost in the universe",<br />,
        "Shaking my knees",<br />,
        "Turn me on, oh my!",<br />,
        "I still have a body",<br />,
        "I come to see the world inside",<br />,
        "Where I won't feel the breeze",<br />,
        "But there's one thing I don't believe in and it's you",<br />,
        "'Cause I feel like I'm nothing in the world",<br />,
        "Maybe",<br />,
        "Chemicals, chemicals",<br />,
        "Are losing",<br />,
        "Maybe",<br />,
        "Chemicals, chemicals",<br />,
        "Are losing you",<br />,
        "Somewhere in my head there is a little crack",<br />,
        "The painful track of what I could have done before you came along",<br />,
        "A strange regret is what I get",<br />,
        "The tables are turned",<br />,
        "We're all gonna burn",<br />,
        "I breathe no air and everyone is there for me",<br />,
        "If only I could see",<br />,
        "Please let me see again",<br />,
        "When trouble comes I know for sure",<br />,
        "The distance in your eye",<br />,
        "I should be on your side",<br />,
        "And you're cold cold like death",<br />,
        "I opened the door",<br />,
        "This time",<br />,
        "Let us shine",<br />,
        "Let us shine",<br />,

         ],

        linkk: 'lm7z0pqRwdw'
    },



    
    {
        author: 'Linkin Park',
        name: "Valentine's Day",
        text: 
        ["My insides all turn to ash",<br />,
        "So slow",<br />,
        "And blow away as I collapsed",<br />,
        "So cold",<br />,
        "A black wind took them away",<br />,
        "From sight",<br />,
        "And now the darkness over day",<br />,
        "That night",<br />,
        'And the clouds above move closer',<br />,
        "Looking so dissatisfied",<br />,
        "But the heartless wind kept blowing, blowing",<br />,
        "I used to be my own protection",<br />,
        "But not now",<br />,
        "'Cause my path has lost direction",<br />,
        "Somehow",<br />,
        "A black wind took you away",<br />,
        "From sight",<br />,
        "And now the darkness over day",<br />,
        "That night",<br />,
        "And the clouds above move closer",<br />,
        "Looking so dissatisfied",<br />,
        "And the ground below grew colder",<br />,
        "As they put you down inside",<br />,
        "But the heartless wind kept blowing, blowing",<br />,
        "So now you're gone",<br />,
        "And I was wrong",<br />,
        "I never knew what it was like",<br />,
        "To be alone",<br />,
        "On a Valentine's Day",<br />,
        "On a Valentine's Day",<br />,
        "On a Valentine's Day",<br />,
        "On a Valentine's Day",<br />,
        "On a Valentine's Day",<br />,
        "(I used to be my own protection)",<br />,
        "On a Valentine's Day",<br />,
        "(But not now)",<br />,
        "On a Valentine's Day",<br />,
        "('Cause my mind has lost direction)",<br />,
        "On a Valentine's Day",<br />,
        "(Somehow)",<br />,
        "On a Valentine's Day",<br />,
        "(I used to be my own protection)",<br />,
        "On a Valentine's Day",<br />,
        "(But not now)",<br />,
        "On a Valentine's Day",<br />,
        "('Cause my mind has lost direction)",<br />,
        "On a Valentine's Day",<br />,
        "(Somehow)",<br />,

         ],

        linkk: 'KAFOpywZbMM'
    },



    {
        author: 'Tove Lo',
        name: "Habbits",
        text: 
        ["I eat my dinner in my bathtub",<br />,
"Then I go to sex clubs",<br />,
"Watching freaky people gettin' it on",<br />,
"It doesn't make me nervous",<br />,
"If anything I'm restless",<br />,
"Yeah, I've been around and I've seen it all",<br />,

"I get home, I got the munchies",<br />,
"Binge on all my Twinkies",<br />,
"Throw up in the tub",<br />,
"Then I go to sleep",<br />,
"And I drank up all my money",<br />,
"Dazed and kinda lonely",<br />,

"You're gone and I gotta stay",<br />,
"High all the time",<br />,
"To keep you off my mind",<br />,
"Ooh-ooh, ooh-ooh",<br />,
"High all the time",<br />,
"To keep you off my mind",<br />,
"Ooh-ooh, ooh-ooh",<br />,
"Spend my days locked in a haze",<br />,
"Tryna forget you babe",<br />,
"I fall back down",<br />,
"Gotta stay high all my life",<br />,
"To forget I'm missing you",<br />,
"Ooh-ooh, ooh-ooh",<br />,

"Pick up daddies at the playground",<br />,
"How I spend my daytime",<br />,
"Loosen up the frown",<br />,
"Make them feel alive",<br />,
"Oh, make it fast and greasy",<br />,
"I'm numb and way too easy",<br />,

"You're gone and I gotta stay",<br />,
"High all the time",<br />,
"To keep you off my mind",<br />,
"Ooh-ooh, ooh-ooh",<br />,
"High all the time",<br />,
"To keep you off my mind",<br />,
"Ooh-ooh, ooh-ooh",<br />,
"Spend my days locked in a haze",<br />,
"Tryna forget you babe",<br />,
"I fall back down",<br />,
"Gotta stay high all my life",<br />,
"To forget I'm missing you",<br />,
"Ooh-ooh, ooh-ooh",<br />,

"Staying in my play pretend",<br />,
"Where the fun ain't got no end",<br />,
"Ooh",<br />,
"Can't go home alone again",<br />,
"Need someone to numb the pain",<br />,
"Ooh",<br />,

"Staying in my play pretend",<br />,
"Where the fun ain't got no end",<br />,
"Ooh",<br />,
"Can't go home alone again",<br />,
"Need someone to numb the pain",<br />,

"You're gone and I gotta stay",<br />,
"High all the time",<br />,
"To keep you off my mind",<br />,
"Ooh-ooh, ooh-ooh",<br />,
"High all the time",<br />,
"To keep you off my mind",<br />,
"Ooh-ooh, ooh-ooh",<br />,
"Spend my days locked in a haze",<br />,
"Tryna forget you babe",<br />,
"I fall back down",<br />,
"Gotta stay high all my life",<br />,
"To forget I'm missing you",<br />,
"Ooh-ooh, ooh-ooh",<br />,

         ],

        linkk: 'oh2LWWORoiM'
    },


    {
        author: 'Tokyo Ghoul OST',
        name: "Yutaka Yamada",
        text: 
        [
            " ",<br />,
         ],
        linkk: '3S1NmtWDVYk'
    },

    {
        author: 'Mono',
        name: "Pure as Snow",
        text: 
            [
                " ",<br />,
             ],
        linkk: 'NWckGUWKFDE'
    },


    {
        author: 'Hammock',
        name: "(Let's Kiss) While All The Stars Are Falling Down",
        text: 
        [
            "Let's kiss while all the stars are falling down",<br />,
            "Tonight we live like no one is around",<br />,
            "Forget the lies that we were told",<br />,
            "Now is the only truth we know",<br />,
            "Tonight we fly while the stars are falling down",<br />,
            "They're falling down",<br />,
            "Down",<br />,
         ],
        linkk: 'P4oV34inoUA'
    },


    {
        author: 'Lilly Wood & The Prick and Robin Schulz',
        name: "Prayer In C (Robin Schulz Remix)",
        text: 
        [
            "Yah, you never said a word",<br />,
            "You didn't send me no letter",<br />,
            "Don't think I could forgive you",<br />,
            
            "See our world is slowly dying",<br />,
            "I'm not wasting no more time",<br />,
            "Don't think I could believe you",<br />,
            
            "Yah, you never said a word",<br />,
            "You didn't send me no letter",<br />,
            "Don't think I could forgive you",<br />,
            
            "See our world is slowly dying",<br />,
            "I'm not wasting no more time",<br />,
            "Don't think I could believe you",<br />,
            
            "Yah, our hands will get more wrinkled",<br />,
            "And our hair will be grey",<br />,
            "Don't think I could forgive you",<br />,
            
            "And see the children are starving",<br />,
            "And their houses were destroyed",<br />,
            "Don't think they could forgive you",<br />,
            
            "Hey, when seas will cover lands",<br />,
            "And when men will be no more",<br />,
            "Don't think you can forgive you",<br />,
            
            "Yah when there'll just be silence",<br />,
            "And when life will be over",<br />,
            "Don't think you will forgive you",<br />,
            
            "Yah, you never said a word",<br />,
            "You didn't send me no letter",<br />,
            "Don't think I could forgive you",<br />,
            
            "See our world is slowly dying",<br />,
            "I'm not wasting no more time",<br />,
            "Don't think I could believe you",<br />,
            
            "Yah, you never said a word",<br />,
            "You didn't send me no letter",<br />,
            "Don't think I could forgive you",<br />,
            
            "See our world is slowly dying",<br />,
            "I'm not wasting no more time",<br />,
           "Don't think I could believe you",<br />,
            
            "Yah, our hands will get more wrinkled",<br />,
            "And our hair will be grey",<br />,
           "Don't think I could forgive you",<br />,
            
            "And see the children are starving",<br />,
            "And their houses were destroyed",<br />,
            "Don't think they could forgive you",<br />,
            
            "Hey, when seas will cover lands",<br />,
            "And when men will be no more",<br />,
            "Don't think you can forgive you",<br />,
            
            "Yah when there'll just be silence",<br />,
            "And when life will be over",<br />,
            "Don't think you will forgive you",<br />,
         ],
        linkk: 'fiore9Z5iUg'
    },




    {
        author: 'Axwell Λ Ingrosso',
        name: "More Than You Know",
        text: 
        [
            "I just need to get it off my chest",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "You should know that, baby, you're the best",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "I saw it coming, from miles away",<br />,
            "I better speak up if I got something to say",<br />,
            "'Cause it ain't over, until she sings",<br />,
            "You had your reasons, you had a few",<br />,
            "But you knew that I would go anywhere for you",<br />,
            "'Cause it ain't over, until she sings",<br />,
            "I just need to get it off my chest",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "You should know that baby you're the best",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Your good intentions are sweet and pure",<br />,
            "But they can never tame a fire like yours",<br />,
            "No it ain't over, until she sings",<br />,
            "Right where you wanted, down on my knees",<br />,
            "You got me begging, pretty baby set me free",<br />,
            "'Cause it ain't over, until she sings",<br />,
            "Come a little closer, let me taste your smile",<br />,
            "Until the morning lights",<br />,
            "Ain't no going back the way you look tonight",<br />,
            "I see it in your eyes",<br />,
            "I just need to get it off my chest",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "You should know that baby you're the best",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "I just need to get it off my chest",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "You should know that baby you're the best",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "I just need to get it off my chest",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
            "You should know that baby you're the best",<br />,
            "Yeah, more than you know",<br />,
            "Yeah, more than you know",<br />,
         ],
        linkk: 'GsF05B8TFWg'
    },



];


    if(this.state.visibility){
    return(
        <div >
            <button style={{color:'#EAD3A8'}} onClick={this.showLyrics} className={`btn btn-outline-light`}>Hide lyrics</button><br />
            <div id="text" className={classes.paper}>
                <div style={{color:'white'}} className={classes.car}>
                {arr[this.props.num].text}
            </div>
            </div>
        </div>

    );
    }else{
        return(
            <div id="text">
                <button style={{color:'#EAD3A8'}} onClick={this.showLyrics} className={`btn btn-outline-light`}>Show lyrics</button><br />
            </div>
    
        );
    }
}

}


const brd= {
    border: '14px double #091A26',
    borderRadius: '5px 20% 5px 5px',
    marginLeft:'7px',

}

export default Lyrics;