import React from 'react';
import classes from './lyrics.module.css';

class Lyrics extends React.Component{
    constructor(props){
        super(props);


        this.state={
            visibility: false
        }
    }

    showLyrics=() => {
        this.setState( state =>{
            if(state.visibility==true){
                return {visibility:false}
            }else{
                return {visibility:true}
            }
        })
    }

render(){
    const arr = [{
        author: 'Lana Del Rey',
        name: 'Never Let Me Go',
        text: 
        ["Hold me in your arms", <br />, "Love me like your best friends did", <br />, "Promise I won't hurt you, kid",
        <br />,"Hold me really tight until the stars look big",<br/>,"Never let me go",<br/>,"All the world is ours",
        <br />,"Like they say in Scarface, kid",<br/>,"You can push your drugs and I can make it big",<br/>,
"Sing at CBGB's, have a real good gig",<br/>,
"Hey, you never know",<br/>,
"'Cause, baby, we were born to live fast and die young",<br/>,
"Born to be bad, have fun",<br/>,
"Honey, you and me can be one",<br/>,
"Just believe, come on",<br/>,
"If you love me hardcore, then don't walk away",<br/>,
"It's a game, boy, I don't wanna play",<br/>,
"I just wanna be yours, like I always say",<br/>,
"Never let me go",<br/>,
"Boy, we're in a world war, let's go all the way",<br/>,
"Play your four-to-the floor, will you walk my way?",<br/>,
"Tell me that you need me more and more everyday",<br/>,
"Never let me go",<br/>,
"Just stay",<br/>,
"We gonna go far",<br/>,
"I can already taste it, kid",<br/>,
"L.A.'s gonna look real good",<br/>,
"Drive me in your car until the sky gets big",<br/>,
"Never let me go",<br/>,
"Send me to the stars",<br/>,
"Tell me when I get there, kid",<br/>,
"I can be your Nancy, you can be my Sid",<br/>,
"Get into some trouble like our parents did",<br/>,
"Hey, they'll never know",<br/>,
"'Cause, baby, we were born to be bad and move on",<br/>,
"Built to go fast and stay strong",<br/>,
"Honey, you and me, and no one",<br/>,
"Just believe, come on",<br/>,
"If you love me hardcore, then don't walk away",<br/>,
"It's a game, boy, I don't wanna play",<br/>,
"I just wanna be yours, like I always say",<br/>,
"Never let me go",<br/>,
"Boy, we're in a world war, let's go all the way",<br/>,
"Play your four-to-the floor, will you walk my way?",<br/>,
"Tell me that you need me more and more everyday",<br/>,
"Never let me go",<br/>,
"Just stay",<br/>,
"I remember when I saw you for the first time",<br/>,
"You were laughing, sparkling like a new dime",<br/>,
"I came over, 'Hello, can you be mine?'",<br/>,
'"Can you be mine? Can you be mine?"',<br/>,
"If you love me hardcore, then don't walk away",<br/>,
"It's a game, boy, I don't wanna play",<br/>,
"I just wanna be yours, like I always say",<br/>,
"Never let me go",<br/>,
"Baby, it's a sweet life, sing it like song",<br/>,
"It's a short trip, only gettin' one",<br/>,
"Who can count on my love more than anyone",<br/>,
"Never let me go",<br/>,
"If you love me hardcore, then don't walk away",<br/>,
"It's a game, boy, I don't wanna play",<br/>,
"I just wanna be yours, like I always say",<br/>,
"Never let me go",<br/>,
"Boy, we're in a world war, let's go all the way",<br/>,
"Play your four-to-the floor, will you walk my way?",<br/>,
"Tell me that you need me more and more everyday",<br/>,
"Never let me go",<br/>,
"Just stay",<br/>],
linkk: 'tDX_XmdccHY'
    },

    {
        author: 'ZAYN ft. Sia',
        name: ' Dusk Till Dawn',
        text: 
        [   "Not tryna be indie", <br />,
            "Not tryna be cool", <br />,
            "Just tryna be in this", <br />,
            "Tell me how you choose", <br />,
            "Can you feel why you're in this", <br />,
            "Can you feel it through", <br />,
            "All of the windows", <br />,
            "Inside this room", <br />,
            "'Cause I wanna touch you, baby", <br />,
            "And I wanna feel you, too", <br />,
            "I wanna see the sunrise and your sins", <br />,
            "Just me and you", <br />,
            "Light it up, on the run", <br />,
            "Let's make love, tonight", <br />,
            "Make it up, fall in love, try", <br />,
            "But you'll never be alone", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll hold you when things go wrong", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "We were shut like a jacket", <br />,
            "So do your zip", <br />,
            "We will roll down the rapids", <br />,
            "To find a wave that fits", <br />,
            "Can you feel where the wind is", <br />,
            "Can you feel it through", <br />,
            "All of the windows", <br />,
            "Inside this room", <br />,
            "'Cause I wanna touch you, baby", <br />,
            "I wanna feel you, too", <br />,
            "I wanna see the sunrise and your sins", <br />,
            "Just me and you", <br />,
            "Light it up, on the run", <br />,
            "Let's make love tonight", <br />,
            "Make it up, fall in love, try", <br />,
            "But you'll never be alone", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll hold you when things go wrong", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "Go, give love to your body", <br />,
            "It's only you that can stop it", <br />,
            "Go, give love to your body", <br />,
            "It's only you that can stop it", <br />,
            "Go, give love to your body", <br />,
            "It's only you that can stop it", <br />,
            "Go, give love to your body", <br />,
            "Go, give love to your body", <br />,
            "But you'll never be alone", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll hold you when things go wrong", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here", <br />,
            "I'll be with you from dusk till dawn", <br />,
            "Baby, I'm right here"],

        linkk: 'tt2k8PGm-TI'
    },








    {
        author: 'James Young',
        name: 'Infinity',
        text: 
        [   "Oh, oh", <br />,
           "Oh, oh, oh", <br />,
           "Oh, oh", <br />,
            "Oh, oh, oh", <br />,
            "Baby, this love, I'll never let it die", <br />,
            "Can't be touched by no one", <br />,
            "I'd like to see 'em try", <br />,
            "I'm a mad man for your touch, girl, I've lost control", <br />,
            "I'm gonna make this last forever, don't tell me it's impossible", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "Oh, darling, my soul", <br />,
            "You know it aches for yours", <br />,
            "And you've been filling this hole, since you were born, oh", <br />,
            "'Cause you're the reason I believe in fate", <br />,
            "You're my paradise", <br />,
            "And I'll do anything to be your love, or be your sacrifice", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "Meet me at the bottom of the ocean", <br />,
            "Where the time is frozen", <br />,
            "Where all the universe is open", <br />,
            "Love isn't random, we are chosen", <br />,
            "And we could wear the same crown", <br />,
            "Keep slowing your heart down", <br />,
            "We are the gods now", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "'Cause I love you for infinity", <br />,
            "(Oh, oh, oh)", <br />,
            "I love you for infinity", <br />,
            "(Oh, oh, oh)" ],

        linkk: 'PWqEPKduGm8'
    },





    {
        author: 'Jp Saxe ft. Julia Michaels',
        name: 'If The World Was Ending',
        text: 
        [   "I was distracted", <br />,
            "And in traffic", <br />,
            "I didn't feel it", <br />,
            "When the earthquake happened", <br />,
            "But it really got me thinkin'", <br />,
            "Were you out drinkin'", <br />,
            "Were you in the living room", <br />,
            "Chillin' watchin' television", <br />,
            "It's been a year now", <br />,
            "Think I've figured out how", <br />,
            "How to let you go and let communication die out", <br />,
            "I know, you know, we know, you weren't down for forever and it's fine", <br />,
            "I know, you know, we know, we weren't meant for each other and it's fine", <br />,
            "But if the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over and you'd stay the night", <br />,
            "Would you love me for the hell of it", <br />,
            "All our fears would be irrelevant", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "The sky'd be falling and I'd hold you tight", <br />,
            "And there wouldn't be a reason why", <br />,
            "We would even have to say goodbye", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "Right?", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "Right?", <br />,
            "I tried to imagine", <br />,
            "Your reaction", <br />,
            "It didn't scare me when the earthquake happened", <br />,
            "But it really got me thinkin'", <br />,
            "That night we went drinkin'", <br />,
            "Stumbled in the house", <br />,
            "And didn't make it past the kitchen", <br />,
            "Ah it's been a year now", <br />,
            "Think I've figured out how", <br />,
            "How to think about you without it rippin' my heart out", <br />,
            "I know, you know, we know, you weren't down for forever and it's fine", <br />,
            "I know, you know, we know, we weren't meant for each other and it's fine", <br />,
            "But if the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over and you'd stay the night", <br />,
            "Would you love me for the hell of it", <br />,
            "All our fears would be irrelevant", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "The sky'd be falling while I'd hold you tight", <br />,
            "No there wouldn't be a reason why", <br />,
            "We would even have to say goodbye", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over right", <br />,
            "You'd come over, you'd come over, you'd come over right", <br />,
            "I know, you know, we know, you weren't down for forever and it's fine", <br />,
            "I know, you know, we know, we weren't meant for each other and it's fine", <br />,
            "But if the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over and you'd stay the night", <br />,
            "Would you love me for the hell of it", <br />,
            "All our fears would be irrelevant", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "The sky'd be falling while I'd hold you tight", <br />,
            "No there wouldn't be a reason why", <br />,
            "We would even have to say goodbye", <br />,
            "If the world was ending", <br />,
            "You'd come over right", <br />,
            "You'd come over, you'd come over, you'd come over right", <br />,
            "If the world was ending", <br />,
            "You'd come over right"
         ],

        linkk: '1jO2wSpAoxA'
    },



    {
        author: 'Lewis Capaldi',
        name: 'Someone You Loved',
        text: 
        [   "I'm going under and this time I fear there's no one to save me", <br />,
        "This all or nothing really got a way of driving me crazy", <br />,
        "I need somebody to heal", <br />,
        "Somebody to know", <br />,
        "Somebody to have", <br />,
        "Somebody to hold", <br />,
        "It's easy to say", <br />,
        "But it's never the same", <br />,
        "I guess I kinda liked the way you numbed all the pain", <br />,
        "Now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
       "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "I'm going under and this time I fear there's no one to turn to", <br />,
        "This all or nothing way of loving got me sleeping without you", <br />,
        "Now, I need somebody to know", <br />,
        "Somebody to heal", <br />,
        "Somebody to have", <br />,
        "Just to know how it feels", <br />,
        "It's easy to say but it's never the same", <br />,
        "I guess I kinda liked the way you helped me escape", <br />,
        "Now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "And I tend to close my eyes when it hurts sometimes", <br />,
        "I fall into your arms", <br />,
        "I'll be safe in your sound 'til I come back around", <br />,
        "For now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "But now the day bleeds", <br />,
        "Into nightfall", <br />,
        "And you're not here", <br />,
        "To get me through it all", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved", <br />,
        "I let my guard down", <br />,
        "And then you pulled the rug", <br />,
        "I was getting kinda used to being someone you loved"
         ],

        linkk: 'zABLecsR5UE'
    },






    {
        author: 'The Young Professionals',
        name: 'Video Games',
        text: 
        [   "Swinging in the backyard", <br />,
        "Pull up in your fast car whistling my name", <br />,
        "Open up a beer", <br />,
        "And you say get over here and play a video game", <br />,
        "I'm in his favorite sun dress", <br />,
        "Watching me get undressed take that body downtown", <br />,
        "I say you the bestest", <br />,
        "Lean in for a big kiss put his favorite perfume on", <br />,
        "Go play your video game", <br />,
        "It's you, it's you, it's all for you", <br />,
        "Everything I do", <br />,
        "I tell you all the time", <br />,
        "Heaven is a place on earth where you", <br />,
        "Tell me all the things you want to do", <br />,
        "I heard that you like the bad girls honey, is that true?", <br />,
        "It's better than I ever even knew", <br />,
        "They say that the world was built for two", <br />,
       "Only worth living if somebody is loving you", <br />,
        "Baby now you do", <br />,
        "Singing in the old bars", <br />,
        "Swinging with the old stars", <br />,
        "Living for the fame", <br />,
        "Kissing in the blue dark", <br />,
        "Playing pool and wild darts", <br />,
        "Video games", <br />,
        "He holds me in his big arms", <br />,
        "Drunk and I am seeing stars", <br />,
        "This is all I think of", <br />,
        "Watching all our friends fall", <br />,
        "In and out of Old Paul's", <br />,
        "This is my idea of fun", <br />,
        "Playing video games", <br />,
        "It's you, it's you, it's all for you", <br />,
        "Everything I do", <br />,
        "I tell you all the time", <br />,
        "Heaven is a place on earth where you", <br />,
        "Tell me all the things you want to do", <br />,
        "I heard that you like the bad girls honey, is that true?", <br />,
        "It's better than I ever even knew", <br />,
        "They say that the world was built for two", <br />,
        "Only worth living if somebody is loving you", <br />,
        "Baby now you do (now you do)", <br />,
        "It's you, it's you, it's all for you", <br />,
        "Everything I do", <br />,
        "I tell you all the time", <br />,
        "Heaven is a place on earth where you", <br />,
        "Tell me all the things you want to do", <br />,
        "I heard that you like the bad girls honey, is that true?", <br />,
        "It's better than I ever even knew", <br />,
        "They say that the world was built for two", <br />,
        "Only worth living if somebody is loving you", <br />,
        "Baby now you do (now you do)", <br />,
        "Now you do (now you do)"
         ],

        linkk: 'sexPTYJ4fbo'
    },




    {
        author: 'James Young',
        name: 'Happiest Year',
        text: 
        [   "I'm really on the ropes this time", <br />,
        "I've been fighting all my life for you", <br />,
        "I never should have said goodbye", <br />,
        "But maybe that's what stupid people do", <br />,
        "'Cause you gave me peace", <br />,
        "And I wasted it", <br />,
        "I'm here to admit", <br />,
        "That you were my medicine", <br />,
        "Oh, I couldn't quit", <br />,
        "And I'm down on my knees again", <br />,
        "Asking", <br />,
        "For nothing", <br />,
        "Thank you for the happiest year of my life", <br />,
        "Thank you for the happiest year of my life, ooh", <br />,
        "Ooh, ooh, ooh", <br />,
       "Don't think I could forgive myself", <br />,
        "I'm sorry for the ways that I used you", <br />,
        "And I could care less right now", <br />,
        "But you know, you hurt me pretty good too", <br />,
        "Yeah, we made each other bleed", <br />,
        "And we tasted it", <br />,
        "I'm here to admit", <br />,
        "That you were my medicine", <br />,
        "Oh, love, I couldn't quit", <br />,
        "And I'm down on my knees again", <br />,
        "Thank you for the happiest year of my life, oh", <br />,
        "Thank you for the happiest year of my life, ooh", <br />,
        "So wake me up when they build that time machine", <br />,
        "I want to go back", <br />,
        "Wake me up when you were sleeping next to me", <br />,
        "'Cause I really loved you, ooh", <br />,
        "Thank you for the happiest year of my life", <br />,
        "Thank you for the happiest year of my life ohh", <br />,
        "Thank you for the happiest year of my life, yeah", <br />,
        "Thank you for the happiest year of my life", <br />,
        "Thank you for the happiest year of my life"
         ],

        linkk: 'v9GLAUWJNG0'
    },


    {
        author: 'TONES AND I',
        name: 'DANCE MONKEY',
        text: 
        [   "They say, oh my god, I see the way you shine", <br />,
        "Take your hands, my dear, and place them both in mine", <br />,
        "You know you stopped me dead while I was passing by", <br />,
        "And now I beg to see you dance just one more time", <br />,
        "Ooh I see you, see you, see you every time", <br />,
        "And, oh my, I, I, I like your style", <br />,
        "You, you make me, make me, make me wanna cry", <br />,
        "And now I beg to see you dance just one more time", <br />,
        
        "So they say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done, I'll make you do it all again", <br />,
        "I said, oh my god, I see you walking by", <br />,
        "Take my hands, my dear, and look me in my eyes", <br />,
        "Just like a monkey I've been dancing my whole life", <br />,
        "But you just beg to see me dance just one more time", <br />,
        "Ooh I see you, see you, see you every time", <br />,
        "And, oh my, I, I, I,", <br />,
        "I like your style", <br />,
        "You, you make me, make me, make me wanna cry", <br />,
        "And now I beg to see you dance just one more time", <br />,
        
        "So they say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        
        "They say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        
        "They say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        "They say", <br />,
        "Dance for me", <br />,
        "Dance for me", <br />,
        "Dance for me oh oh oh", <br />,
        "I've never seen anybody do the things you do before", <br />,
        "They say", <br />,
        "Move for me", <br />,
        "Move for me", <br />,
        "Move for me ay ay ay", <br />,
        "And when you're done I'll make you do it all again", <br />,
        "All again "
         ],

        linkk: 'q0hyYWKXF0Q'
    },


    {
        author: 'Pascal Letoublon',
        name: 'Friendships',
        text: "",

        linkk: '5rmb7WhmW30'
    },


    {
        author: 'Christina Perri',
        name: 'Human',
        text: ["I can hold my breath", <br />,
        "I can bite my tongue", <br />,
        "I can stay awake for days", <br />,
        "If that's what you want", <br />,
        "Be your number one", <br />,
        "I can fake a smile", <br />,
        "I can force a laugh", <br />,
        "I can dance and play the part", <br />,
        "If that's what you ask", <br />,
       "Give you all I am", <br />,
        "I can do it", <br />,
        "I can do it", <br />,
        "I can do it", <br />,
        "But I'm only human", <br />,
        "And I bleed when I fall down", <br />,
        "I'm only human", <br />,
        "And I crash and I break down", <br />,
        "Your words in my head, knives in my heart", <br />,
        "You build me up and then I fall apart", <br />,
        "'Cause I'm only human, yeah", <br />,
        "I can turn it on", <br />,
        "Be a good machine", <br />,
        "I can hold the weight of worlds", <br />,
        "If that's what you need", <br />,
        "Be your everything", <br />,
        "I can do it", <br />,
        "I can do it", <br />,
        "I'll get through it", <br />,
        "But I'm only human", <br />,
        "And I bleed when I fall down", <br />,
        "I'm only human", <br />,
        "And I crash and I break down", <br />,
        "Your words in my head, knives in my heart", <br />,
        "You build me up and then I fall apart", <br />,
        "'Cause I'm only human, yeah", <br />,
        "I'm only human", <br />,
        "I'm only human", <br />,
        "Just a little human", <br />,
        "I can take so much", <br />,
        "Until I've had enough", <br />,
        "'Cause I'm only human", <br />,
        "And I bleed when I fall down", <br />,
        "I'm only human", <br />,
        "And I crash and I break down", <br />,
        "Your words in my head, knives in my heart", <br />,
        "You build me up and then I fall apart", <br />,
        "'Cause I'm only human, yeah"],

        linkk: '5rmb7WhmW30'
    },


    {
        author: 'James Bay',
        name: 'Let It Go',
        text: ["From walking home and talking loads", <br />,
        "To seeing shows in evening clothes with you", <br />,
        "From nervous touch and getting drunk", <br />,
        "To staying up and waking up with you", <br />,
        "Now we're slipping near the edge", <br />,
        "Holding something we don't need", <br />,
        "Oh, this delusion in our heads", <br />,
        "Is gonna bring us to our knees", <br />,
        "So come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "Everything that's broke", <br />,
        "Leave it to the breeze", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "And I'll be me", <br />,
        "From throwing clothes across the floor", <br />,
        "To teeth and claws and slamming doors at you", <br />,
        "If this is all we're living for", <br />,
        "Why are we doing it, doing it, doing it anymore?", <br />,
        "I used to recognize myself", <br />,
        "It's funny how reflections change", <br />,
        "When we're becoming something else", <br />,
        "I think it's time to walk away", <br />,
        "So come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "Everything that's broke", <br />,
        "Leave it to the breeze", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "And I'll be me", <br />,
        "Tryna fit your hand inside mine", <br />,
        "When we know it just don't belong", <br />,
        "There's no force on earth", <br />,
        "Could make it feel right, no", <br />,
        "Tryna push this problem up the hill", <br />,
        "When it's just too heavy to hold", <br />,
        "Think now is the time to let it slide", <br />,
        "So come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "Everything that's broke", <br />,
        "Leave it to the breeze", <br />,
        "Let the ashes fall", <br />,
        "Forget about me", <br />,
        "Come on, let it go", <br />,
        "Just let it be", <br />,
        "Why don't you be you", <br />,
        "And I'll be me", <br />,
        "And I'll be me"],

        linkk: 'GsPq9mzFNGY'
    },





    {
        author: 'Alec Benjamin',
        name: 'The Water Fountain',
        text: 
        ["She told me that she loved me by the water fountain", <br />,
        "She told me that she loved me and she didn't love him", <br />,
        "And that was really lovely 'cause it was innocent", <br />,
        "But now she's got a cup with something else in it", <br />,
        "It's getting kind of blurry at a quarter-past-ten", <br />,
        "And he was in a hurry to be touching her skin", <br />,
        "She's feeling kind of dirty when she's dancing with him", <br />,
        "Forgetting what she told me by the water fountain", <br />,
        "Now he's grabbing her hips, and pulling her in", <br />,
        "Kissing her lips, and whispering in her ear", <br />,
        "And she knows that she shouldn't listen", <br />,
        "And that she should be with me by the water fountain", <br />,
        "She couldn't be at home in the night time because", <br />,
        "It made her feel alone, but at that time she was too young", <br />,
        "I was too young", <br />,
        "I should've built a home with a fountain for us", <br />,
        "The moment that she told me that she was in love too young", <br />,
        "I was too young", <br />,
        "Too young, too young", <br />,
        "Too young, young", <br />,
        "And if she ever goes back to the water fountain", <br />,
        "The handle will be broken and the rust set in", <br />,
        "But my hand, it will be open and I'll try to fix it", <br />,
        "My heart, it will be open and I'll try to give it", <br />,
        "Now I'm grabbing her hips, and pulling her in", <br />,
        "Kissing her lips, and whispering in her ear", <br />,
        "And I know that it's only a wish", <br />,
        "And that we're not standing by the water fountain", <br />,
        "Too young, too young", <br />,
        "Too young, young", <br />,
        "She couldn't be at home in the night time because", <br />,
        "It made her feel alone but at that time she was too young", <br />,
        "I was too young", <br />,
        "I should've built a home with a fountain for us", <br />,
        "The moment that she told me that she was in love too young", <br />,
        "I was too young", <br />,
        "Too young, too young", <br />,
        "Too young, young", <br />,
        "I should've built a home with a fountain for us", <br />,
        "(Too young) the moment that she told me that she was in love", <br />,
        "(Too young) too young", <br />,
        "(Young) I was too young"],
        linkk: '5ado75KpV9w'
    },

    


    {
        author: 'LP',
        name: 'Lost On You',
        text: ["When you get older, plainer, saner", <br />,
        "When you remember all the danger we came from", <br />,
        "Burning like embers, falling, tender", <br />,
        "Long before the days of no surrender", <br />,
        "Years ago and well you know", <br />,
        "Smoke 'em if you got 'em", <br />,
        "'Cause it's going down", <br />,
        "All I ever wanted was you", <br />,
        "I'll never get to heaven", <br />,
        "'Cause I don't know how", <br />,
        "Let's raise a glass or two", <br />,
        "To all the things I've lost on you", <br />,
        "Oh oh", <br />,
        "Tell me are they lost on you?", <br />,
        "Oh oh", <br />,
        "Just that you could cut me loose", <br />,
        "Oh oh", <br />,
        "After everything I've lost on you", <br />,
        "Is that lost on you?", <br />,
        "Oh oh", <br />,
        "Is that lost on you?", <br />,
        "Oh oh", <br />,
        "Baby, is that lost on you?", <br />,
        "Is that lost on you?", <br />,
        "Wishing I could see the machinations", <br />,
        "Understand the toil of expectations in your mind", <br />,
        "Hold me like you never lost your patience", <br />,
        "Tell me that you love me more than hate me all the time", <br />,
        "And you're still mine", <br />,
        "So smoke 'em if you've got 'em", <br />,
        "'Cause it's going down", <br />,
        "All I ever wanted was you", <br />,
        "Let's take a drink of heaven", <br />,
        "This can turn around", <br />,
        "Let's raise a glass or two", <br />,
        "To all the things I've lost on you", <br />,
        "Oh oh", <br />,
        "Tell me are they lost on you?", <br />,
        "Oh oh", <br />,
        "Just that you could cut me loose", <br />,
        "Oh oh", <br />,
        "After everything I've lost on you", <br />,
        "Is that lost on you?", <br />,
        "Oh oh", <br />,
        "Is that lost on you?", <br />,
        "Oh oh, oh oh", <br />,
        "Bab, is that lost on you?", <br />,
        "Is that lost on you?", <br />,
        "Let's raise a glass or two", <br />,
        "To all the things I've lost on you", <br />,
        "Oh oh", <br />,
        "Tell me are they lost on you?", <br />,
        "Oh oh", <br />,
        "Just that you cold cut me loose", <br />,
        "Oh oh", <br />,
       "After everything I've lost on you", <br />,
        "Is that lost on you?", <br />,
        "Is that lost on you?"],

        linkk: 'hn3wJ1_1Zsg'
    },


    {
        author: 'Frames',
        name: "Don't Stay Here",
        text: "",
        linkk: '1knh-_SYrfQ'
    },



];


    if(this.state.visibility){
    return(
        <div >
            <button onClick={this.showLyrics} className={`btn btn-outline-danger`}>Hide lyrics</button><br />
            <div className={classes.car}>
                {arr[this.props.num].text}
            </div>
        </div>

    );
    }else{
        return(
            <div>
                <button onClick={this.showLyrics} className={`btn btn-outline-secondary`}>Show lyrics</button><br />
            </div>
    
        );
    }
}

}

export default Lyrics;